
language: objective-c

before_install:
    - export LANG=en_US.UTF-8
    - env
    - locale
    - gem install cocoapods --quiet
    - pod --version
    - pod setup --silent
    - pod repo update --silent

script:
    - pod lib lint
    - cd Demo
    - pod update
    - xctool -workspace NBUKitDemo.xcworkspace -scheme 'NBUKitDemo' -configuration Release -sdk iphonesimulator -arch i386 build
