language: objective-c
before_install: "cd /usr/local/Library/ && git stash && git clean -f && cd - && git submodule init && git submodule update && sudo gem update --system && sudo gem install bundler && bundle install && brew update && brew install xctool"
script: "bundle exec rake test --trace"
